// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Contact struct {
	UserID            string    `json:"user_id"`
	ContactID         string    `json:"contact_id"`
	LastInteractionAt time.Time `json:"last_interaction_at"`
}

type Letter struct {
	ID                        string         `json:"id"`
	SenderID                  string         `json:"sender_id"`
	RecipientID               sql.NullString `json:"recipient_id"`
	RecipientNameUnregistered sql.NullString `json:"recipient_name_unregistered"`
	Subject                   string         `json:"subject"`
	Content                   string         `json:"content"`
	DeliveryAt                time.Time      `json:"delivery_at"`
	CreatedAt                 time.Time      `json:"created_at"`
	ReadAt                    sql.NullTime   `json:"read_at"`
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}
