// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createLetter = `-- name: CreateLetter :one
INSERT INTO letters (id, sender_id, recipient_id, recipient_name_unregistered, subject, content, delivery_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, sender_id, recipient_id, recipient_name_unregistered, subject, content, delivery_at, created_at, read_at
`

type CreateLetterParams struct {
	ID                        string         `json:"id"`
	SenderID                  string         `json:"sender_id"`
	RecipientID               sql.NullString `json:"recipient_id"`
	RecipientNameUnregistered sql.NullString `json:"recipient_name_unregistered"`
	Subject                   string         `json:"subject"`
	Content                   string         `json:"content"`
	DeliveryAt                time.Time      `json:"delivery_at"`
}

func (q *Queries) CreateLetter(ctx context.Context, arg CreateLetterParams) (Letter, error) {
	row := q.db.QueryRowContext(ctx, createLetter,
		arg.ID,
		arg.SenderID,
		arg.RecipientID,
		arg.RecipientNameUnregistered,
		arg.Subject,
		arg.Content,
		arg.DeliveryAt,
	)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.RecipientNameUnregistered,
		&i.Subject,
		&i.Content,
		&i.DeliveryAt,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_resets (user_id, token, expires_at)
VALUES (?, ?, ?)
`

type CreatePasswordResetParams struct {
	UserID    string    `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordReset, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, password_hash)
VALUES (?, ?, ?, ?)
RETURNING id, username, email, password_hash, created_at
`

type CreateUserParams struct {
	ID           string         `json:"id"`
	Username     string         `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResets = `-- name: DeleteExpiredPasswordResets :exec
DELETE FROM password_resets
WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredPasswordResets(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasswordResets, expiresAt)
	return err
}

const deletePasswordReset = `-- name: DeletePasswordReset :exec
DELETE FROM password_resets
WHERE token = ?
`

func (q *Queries) DeletePasswordReset(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deletePasswordReset, token)
	return err
}

const getContactsWithLastLetterMetadata = `-- name: GetContactsWithLastLetterMetadata :many
SELECT 
    c.contact_id,
    u.username AS contact_username,
    c.last_interaction_at,
    l.id AS last_letter_id,
    l.sender_id AS last_letter_sender_id,
    l.delivery_at AS last_letter_delivery_at,
    l.created_at AS last_letter_created_at
FROM contacts c
JOIN users u ON c.contact_id = u.id
LEFT JOIN letters l ON l.id = (
    SELECT id FROM letters 
    WHERE (sender_id = c.user_id AND recipient_id = c.contact_id)
       OR (sender_id = c.contact_id AND recipient_id = c.user_id)
    ORDER BY created_at DESC 
    LIMIT 1
)
WHERE c.user_id = ?
`

type GetContactsWithLastLetterMetadataRow struct {
	ContactID            string         `json:"contact_id"`
	ContactUsername      string         `json:"contact_username"`
	LastInteractionAt    time.Time      `json:"last_interaction_at"`
	LastLetterID         sql.NullString `json:"last_letter_id"`
	LastLetterSenderID   sql.NullString `json:"last_letter_sender_id"`
	LastLetterDeliveryAt sql.NullTime   `json:"last_letter_delivery_at"`
	LastLetterCreatedAt  sql.NullTime   `json:"last_letter_created_at"`
}

func (q *Queries) GetContactsWithLastLetterMetadata(ctx context.Context, userID string) ([]GetContactsWithLastLetterMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, getContactsWithLastLetterMetadata, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactsWithLastLetterMetadataRow
	for rows.Next() {
		var i GetContactsWithLastLetterMetadataRow
		if err := rows.Scan(
			&i.ContactID,
			&i.ContactUsername,
			&i.LastInteractionAt,
			&i.LastLetterID,
			&i.LastLetterSenderID,
			&i.LastLetterDeliveryAt,
			&i.LastLetterCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInbox = `-- name: GetInbox :many
SELECT 
    l.id, 
    l.sender_id, 
    u.username AS sender_username,
    l.recipient_id, 
    l.recipient_name_unregistered, 
    l.subject, 
    l.content, 
    l.delivery_at, 
    l.created_at,
    l.read_at
FROM letters l
JOIN users u ON l.sender_id = u.id
WHERE l.recipient_id = ? AND l.delivery_at <= ?
ORDER BY l.delivery_at DESC
`

type GetInboxParams struct {
	RecipientID sql.NullString `json:"recipient_id"`
	DeliveryAt  time.Time      `json:"delivery_at"`
}

type GetInboxRow struct {
	ID                        string         `json:"id"`
	SenderID                  string         `json:"sender_id"`
	SenderUsername            string         `json:"sender_username"`
	RecipientID               sql.NullString `json:"recipient_id"`
	RecipientNameUnregistered sql.NullString `json:"recipient_name_unregistered"`
	Subject                   string         `json:"subject"`
	Content                   string         `json:"content"`
	DeliveryAt                time.Time      `json:"delivery_at"`
	CreatedAt                 time.Time      `json:"created_at"`
	ReadAt                    sql.NullTime   `json:"read_at"`
}

func (q *Queries) GetInbox(ctx context.Context, arg GetInboxParams) ([]GetInboxRow, error) {
	rows, err := q.db.QueryContext(ctx, getInbox, arg.RecipientID, arg.DeliveryAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInboxRow
	for rows.Next() {
		var i GetInboxRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.SenderUsername,
			&i.RecipientID,
			&i.RecipientNameUnregistered,
			&i.Subject,
			&i.Content,
			&i.DeliveryAt,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLetterByID = `-- name: GetLetterByID :one
SELECT 
    l.id,
    l.sender_id,
    su.username AS sender_username,
    l.recipient_id,
    ru.username AS recipient_username,
    l.recipient_name_unregistered,
    l.subject,
    l.content,
    l.delivery_at,
    l.created_at,
    l.read_at
FROM letters l
JOIN users su ON l.sender_id = su.id
LEFT JOIN users ru ON l.recipient_id = ru.id
WHERE l.id = ? LIMIT 1
`

type GetLetterByIDRow struct {
	ID                        string         `json:"id"`
	SenderID                  string         `json:"sender_id"`
	SenderUsername            string         `json:"sender_username"`
	RecipientID               sql.NullString `json:"recipient_id"`
	RecipientUsername         sql.NullString `json:"recipient_username"`
	RecipientNameUnregistered sql.NullString `json:"recipient_name_unregistered"`
	Subject                   string         `json:"subject"`
	Content                   string         `json:"content"`
	DeliveryAt                time.Time      `json:"delivery_at"`
	CreatedAt                 time.Time      `json:"created_at"`
	ReadAt                    sql.NullTime   `json:"read_at"`
}

func (q *Queries) GetLetterByID(ctx context.Context, id string) (GetLetterByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLetterByID, id)
	var i GetLetterByIDRow
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.SenderUsername,
		&i.RecipientID,
		&i.RecipientUsername,
		&i.RecipientNameUnregistered,
		&i.Subject,
		&i.Content,
		&i.DeliveryAt,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const getOpenLettersForUnregistered = `-- name: GetOpenLettersForUnregistered :many
SELECT 
    l.id, 
    l.sender_id, 
    u.username AS sender_username,
    l.recipient_name_unregistered, 
    l.subject, 
    l.content, 
    l.delivery_at, 
    l.created_at,
    l.read_at
FROM letters l
JOIN users u ON l.sender_id = u.id
WHERE l.recipient_id IS NULL 
  AND l.recipient_name_unregistered = ? 
  AND l.delivery_at <= ?
ORDER BY l.delivery_at DESC
`

type GetOpenLettersForUnregisteredParams struct {
	RecipientNameUnregistered sql.NullString `json:"recipient_name_unregistered"`
	DeliveryAt                time.Time      `json:"delivery_at"`
}

type GetOpenLettersForUnregisteredRow struct {
	ID                        string         `json:"id"`
	SenderID                  string         `json:"sender_id"`
	SenderUsername            string         `json:"sender_username"`
	RecipientNameUnregistered sql.NullString `json:"recipient_name_unregistered"`
	Subject                   string         `json:"subject"`
	Content                   string         `json:"content"`
	DeliveryAt                time.Time      `json:"delivery_at"`
	CreatedAt                 time.Time      `json:"created_at"`
	ReadAt                    sql.NullTime   `json:"read_at"`
}

func (q *Queries) GetOpenLettersForUnregistered(ctx context.Context, arg GetOpenLettersForUnregisteredParams) ([]GetOpenLettersForUnregisteredRow, error) {
	rows, err := q.db.QueryContext(ctx, getOpenLettersForUnregistered, arg.RecipientNameUnregistered, arg.DeliveryAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOpenLettersForUnregisteredRow
	for rows.Next() {
		var i GetOpenLettersForUnregisteredRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.SenderUsername,
			&i.RecipientNameUnregistered,
			&i.Subject,
			&i.Content,
			&i.DeliveryAt,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutbox = `-- name: GetOutbox :many
SELECT 
    l.id,
    l.sender_id,
    l.recipient_id,
    u.username AS recipient_username,
    l.recipient_name_unregistered,
    l.subject,
    l.content,
    l.delivery_at,
    l.created_at,
    l.read_at
FROM letters l
LEFT JOIN users u ON l.recipient_id = u.id
WHERE l.sender_id = ?
ORDER BY l.created_at DESC
`

type GetOutboxRow struct {
	ID                        string         `json:"id"`
	SenderID                  string         `json:"sender_id"`
	RecipientID               sql.NullString `json:"recipient_id"`
	RecipientUsername         sql.NullString `json:"recipient_username"`
	RecipientNameUnregistered sql.NullString `json:"recipient_name_unregistered"`
	Subject                   string         `json:"subject"`
	Content                   string         `json:"content"`
	DeliveryAt                time.Time      `json:"delivery_at"`
	CreatedAt                 time.Time      `json:"created_at"`
	ReadAt                    sql.NullTime   `json:"read_at"`
}

func (q *Queries) GetOutbox(ctx context.Context, senderID string) ([]GetOutboxRow, error) {
	rows, err := q.db.QueryContext(ctx, getOutbox, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutboxRow
	for rows.Next() {
		var i GetOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.RecipientUsername,
			&i.RecipientNameUnregistered,
			&i.Subject,
			&i.Content,
			&i.DeliveryAt,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordResetByToken = `-- name: GetPasswordResetByToken :one
SELECT user_id, token, expires_at FROM password_resets
WHERE token = ? LIMIT 1
`

func (q *Queries) GetPasswordResetByToken(ctx context.Context, token string) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetByToken, token)
	var i PasswordReset
	err := row.Scan(&i.UserID, &i.Token, &i.ExpiresAt)
	return i, err
}

const getPendingIncoming = `-- name: GetPendingIncoming :many
SELECT 
    l.id, 
    l.sender_id, 
    u.username AS sender_username,
    l.recipient_id, 
    l.subject, 
    l.delivery_at, 
    l.created_at
FROM letters l
JOIN users u ON l.sender_id = u.id
WHERE l.recipient_id = ? AND l.delivery_at > ?
ORDER BY l.delivery_at ASC
`

type GetPendingIncomingParams struct {
	RecipientID sql.NullString `json:"recipient_id"`
	DeliveryAt  time.Time      `json:"delivery_at"`
}

type GetPendingIncomingRow struct {
	ID             string         `json:"id"`
	SenderID       string         `json:"sender_id"`
	SenderUsername string         `json:"sender_username"`
	RecipientID    sql.NullString `json:"recipient_id"`
	Subject        string         `json:"subject"`
	DeliveryAt     time.Time      `json:"delivery_at"`
	CreatedAt      time.Time      `json:"created_at"`
}

// Retrieve metadata for incoming letters that are still in transit (content is NOT returned)
func (q *Queries) GetPendingIncoming(ctx context.Context, arg GetPendingIncomingParams) ([]GetPendingIncomingRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingIncoming, arg.RecipientID, arg.DeliveryAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingIncomingRow
	for rows.Next() {
		var i GetPendingIncomingRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.SenderUsername,
			&i.RecipientID,
			&i.Subject,
			&i.DeliveryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, created_at FROM users
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, created_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, created_at FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const markLetterAsRead = `-- name: MarkLetterAsRead :exec
UPDATE letters
SET read_at = ?
WHERE id = ? AND read_at IS NULL
`

type MarkLetterAsReadParams struct {
	ReadAt sql.NullTime `json:"read_at"`
	ID     string       `json:"id"`
}

func (q *Queries) MarkLetterAsRead(ctx context.Context, arg MarkLetterAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markLetterAsRead, arg.ReadAt, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash sql.NullString `json:"password_hash"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const upsertContact = `-- name: UpsertContact :exec
INSERT INTO contacts (user_id, contact_id, last_interaction_at)
VALUES (?, ?, ?)
ON CONFLICT(user_id, contact_id) DO UPDATE SET
last_interaction_at = excluded.last_interaction_at
`

type UpsertContactParams struct {
	UserID            string    `json:"user_id"`
	ContactID         string    `json:"contact_id"`
	LastInteractionAt time.Time `json:"last_interaction_at"`
}

func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) error {
	_, err := q.db.ExecContext(ctx, upsertContact, arg.UserID, arg.ContactID, arg.LastInteractionAt)
	return err
}
