// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createLetter = `-- name: CreateLetter :one
INSERT INTO letters (id, sender_id, recipient_id, recipient_name_unregistered, subject, content, delivery_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, sender_id, recipient_id, recipient_name_unregistered, subject, content, delivery_at, created_at
`

type CreateLetterParams struct {
	ID                        string         `json:"id"`
	SenderID                  string         `json:"sender_id"`
	RecipientID               sql.NullString `json:"recipient_id"`
	RecipientNameUnregistered sql.NullString `json:"recipient_name_unregistered"`
	Subject                   string         `json:"subject"`
	Content                   string         `json:"content"`
	DeliveryAt                time.Time      `json:"delivery_at"`
}

func (q *Queries) CreateLetter(ctx context.Context, arg CreateLetterParams) (Letter, error) {
	row := q.db.QueryRowContext(ctx, createLetter,
		arg.ID,
		arg.SenderID,
		arg.RecipientID,
		arg.RecipientNameUnregistered,
		arg.Subject,
		arg.Content,
		arg.DeliveryAt,
	)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.RecipientNameUnregistered,
		&i.Subject,
		&i.Content,
		&i.DeliveryAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username)
VALUES (?, ?)
RETURNING id, username, created_at
`

type CreateUserParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}

const getContactsWithLastLetterMetadata = `-- name: GetContactsWithLastLetterMetadata :many
SELECT 
    c.contact_id,
    u.username AS contact_username,
    c.last_interaction_at,
    l.id AS last_letter_id,
    l.sender_id AS last_letter_sender_id,
    l.delivery_at AS last_letter_delivery_at,
    l.created_at AS last_letter_created_at
FROM contacts c
JOIN users u ON c.contact_id = u.id
LEFT JOIN letters l ON l.id = (
    SELECT id FROM letters 
    WHERE (sender_id = c.user_id AND recipient_id = c.contact_id)
       OR (sender_id = c.contact_id AND recipient_id = c.user_id)
    ORDER BY created_at DESC 
    LIMIT 1
)
WHERE c.user_id = ?
`

type GetContactsWithLastLetterMetadataRow struct {
	ContactID            string         `json:"contact_id"`
	ContactUsername      string         `json:"contact_username"`
	LastInteractionAt    time.Time      `json:"last_interaction_at"`
	LastLetterID         sql.NullString `json:"last_letter_id"`
	LastLetterSenderID   sql.NullString `json:"last_letter_sender_id"`
	LastLetterDeliveryAt sql.NullTime   `json:"last_letter_delivery_at"`
	LastLetterCreatedAt  sql.NullTime   `json:"last_letter_created_at"`
}

func (q *Queries) GetContactsWithLastLetterMetadata(ctx context.Context, userID string) ([]GetContactsWithLastLetterMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, getContactsWithLastLetterMetadata, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactsWithLastLetterMetadataRow
	for rows.Next() {
		var i GetContactsWithLastLetterMetadataRow
		if err := rows.Scan(
			&i.ContactID,
			&i.ContactUsername,
			&i.LastInteractionAt,
			&i.LastLetterID,
			&i.LastLetterSenderID,
			&i.LastLetterDeliveryAt,
			&i.LastLetterCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInbox = `-- name: GetInbox :many
SELECT id, sender_id, recipient_id, recipient_name_unregistered, subject, content, delivery_at, created_at
FROM letters
WHERE recipient_id = ? AND delivery_at <= ?
ORDER BY delivery_at DESC
`

type GetInboxParams struct {
	RecipientID sql.NullString `json:"recipient_id"`
	DeliveryAt  time.Time      `json:"delivery_at"`
}

func (q *Queries) GetInbox(ctx context.Context, arg GetInboxParams) ([]Letter, error) {
	rows, err := q.db.QueryContext(ctx, getInbox, arg.RecipientID, arg.DeliveryAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Letter
	for rows.Next() {
		var i Letter
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.RecipientNameUnregistered,
			&i.Subject,
			&i.Content,
			&i.DeliveryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLetterByID = `-- name: GetLetterByID :one
SELECT id, sender_id, recipient_id, recipient_name_unregistered, subject, content, delivery_at, created_at FROM letters
WHERE id = ? LIMIT 1
`

func (q *Queries) GetLetterByID(ctx context.Context, id string) (Letter, error) {
	row := q.db.QueryRowContext(ctx, getLetterByID, id)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.RecipientNameUnregistered,
		&i.Subject,
		&i.Content,
		&i.DeliveryAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenLettersForUnregistered = `-- name: GetOpenLettersForUnregistered :many
SELECT id, sender_id, recipient_name_unregistered, subject, content, delivery_at, created_at
FROM letters
WHERE recipient_id IS NULL 
  AND recipient_name_unregistered = ? 
  AND delivery_at <= ?
ORDER BY delivery_at DESC
`

type GetOpenLettersForUnregisteredParams struct {
	RecipientNameUnregistered sql.NullString `json:"recipient_name_unregistered"`
	DeliveryAt                time.Time      `json:"delivery_at"`
}

type GetOpenLettersForUnregisteredRow struct {
	ID                        string         `json:"id"`
	SenderID                  string         `json:"sender_id"`
	RecipientNameUnregistered sql.NullString `json:"recipient_name_unregistered"`
	Subject                   string         `json:"subject"`
	Content                   string         `json:"content"`
	DeliveryAt                time.Time      `json:"delivery_at"`
	CreatedAt                 time.Time      `json:"created_at"`
}

func (q *Queries) GetOpenLettersForUnregistered(ctx context.Context, arg GetOpenLettersForUnregisteredParams) ([]GetOpenLettersForUnregisteredRow, error) {
	rows, err := q.db.QueryContext(ctx, getOpenLettersForUnregistered, arg.RecipientNameUnregistered, arg.DeliveryAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOpenLettersForUnregisteredRow
	for rows.Next() {
		var i GetOpenLettersForUnregisteredRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientNameUnregistered,
			&i.Subject,
			&i.Content,
			&i.DeliveryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutbox = `-- name: GetOutbox :many
SELECT id, sender_id, recipient_id, recipient_name_unregistered, subject, content, delivery_at, created_at FROM letters
WHERE sender_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetOutbox(ctx context.Context, senderID string) ([]Letter, error) {
	rows, err := q.db.QueryContext(ctx, getOutbox, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Letter
	for rows.Next() {
		var i Letter
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.RecipientNameUnregistered,
			&i.Subject,
			&i.Content,
			&i.DeliveryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingIncoming = `-- name: GetPendingIncoming :many
SELECT id, sender_id, recipient_id, subject, delivery_at, created_at
FROM letters
WHERE recipient_id = ? AND delivery_at > ?
ORDER BY delivery_at ASC
`

type GetPendingIncomingParams struct {
	RecipientID sql.NullString `json:"recipient_id"`
	DeliveryAt  time.Time      `json:"delivery_at"`
}

type GetPendingIncomingRow struct {
	ID          string         `json:"id"`
	SenderID    string         `json:"sender_id"`
	RecipientID sql.NullString `json:"recipient_id"`
	Subject     string         `json:"subject"`
	DeliveryAt  time.Time      `json:"delivery_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

// Retrieve metadata for incoming letters that are still in transit (content is NOT returned)
func (q *Queries) GetPendingIncoming(ctx context.Context, arg GetPendingIncomingParams) ([]GetPendingIncomingRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingIncoming, arg.RecipientID, arg.DeliveryAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingIncomingRow
	for rows.Next() {
		var i GetPendingIncomingRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.Subject,
			&i.DeliveryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, created_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, created_at FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}

const upsertContact = `-- name: UpsertContact :exec
INSERT INTO contacts (user_id, contact_id, last_interaction_at)
VALUES (?, ?, ?)
ON CONFLICT(user_id, contact_id) DO UPDATE SET
last_interaction_at = excluded.last_interaction_at
`

type UpsertContactParams struct {
	UserID            string    `json:"user_id"`
	ContactID         string    `json:"contact_id"`
	LastInteractionAt time.Time `json:"last_interaction_at"`
}

func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) error {
	_, err := q.db.ExecContext(ctx, upsertContact, arg.UserID, arg.ContactID, arg.LastInteractionAt)
	return err
}
